### ISSUE TITLE
Can we support PPX on x86 Mac?

### ISSUE THREAD

**Issue by ken-miyashita** [cca-io/rescript-material-ui#119]
Hi. I'm a newbie in ReScript + react, and just started investigating your interesting material-ui binding.
Can you make a binary of PPX for Mac?
- platform = darwin
- arch = x64

**Comment by jsiebern** [comment]
Hi. The distributed NPM package should contain the binary you're asking for  (and should automatically copy it into place on install). You can use it by just following the instructions from this page: https://jsiebern.github.io/bs-material-ui/docs/styles-ppx/installation
