### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by joshgodsiff** [cca-io/rescript-material-ui#124]
Any chance an up-to-date version of this could be pushed up to NPM? The dependency on `bs-platform@"^8.2.0` in the currently published version means those of us on `9.0.2` can't easily use this at the moment, whereas that seems to be fixed in the current git repo code.

**Comment by wildlifehexagon** [comment]
Also wondering about this. Is there a workaround in the meantime? I'm looking to use these Material UI bindings in a new ReScript project.

**Comment by cknitt** [comment]
Yes, this should happen within the next 1-2 weeks. See also https://github.com/cca-io/rescript-material-ui#roadmap.

In the meantime, you can keep using the previous version (if you hold off migrating from reason-react to @rescript/react).

**Comment by cknitt** [comment]
Just published version 2.1.0.
