### ISSUE TITLE
Problem with GLIBC version since version 2.1.0

### ISSUE THREAD

**Issue by FilipKittnar** [cca-io/rescript-material-ui#141]
When I update the `@jsiebern/bs-material-ui-ppx` to a version higher than 2.0.1 (or to the `rescript-material-ui-ppx`) and try to build my project in a docker container running on the latest official "node" image, I get this error: `version GLIBC_2.29 not found (required by` ... which is caused by the ppx library.

**Comment by cknitt** [comment]
Thanks for the report! This is the same problem as in https://github.com/rescript-lang/rescript-vscode/issues/216.

We will change the CI build to use `ubuntu-18.04` instead of `ubuntu-latest` to fix this.

**Comment by FilipKittnar** [comment]
Hello,
is there any plan for when is this fix going to be released? The last version is still 2.1.2 from May.

**Comment by fhammerschmidt** [comment]
Sorry, we are currently very busy. There are some open issues which prevent us from doing the next release. We try to fix them as soon as possible.

I cannot give you any promises, but we are aiming for somewhere in November.
