### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by cknitt** [cca-io/rescript-material-ui#153]
- [x] Remove ReScript vs. ReasonML section
- [x] Naming section: do not advertise `MaterialUi_[COMPONENT_NAME]` anymore, we should be moving to `MaterialUi.[COMPONENT_NAME]`.
- [x] Union Values section incorrect (identifiers in the bindings are now 1:1 with JS)
- [x] Styles documentation: describe different solutions for styling (including bs-css and Tailwind) and state that the PPX is not recommended

**Comment by fhammerschmidt** [comment]
Last one done with huge 3.0.0 PR (#177)
