### ISSUE TITLE
Possibly wrong types for ThemeOptions.AppBarClassKey make arguments

### ISSUE THREAD

**Issue by Deydim** [cca-io/rescript-material-ui#161]
Hello, 
I am new to MUI and ReScript but I have been trying your bindings for an example project and absolutely love what you are doing! 

Just so you know, these might need type `ReactDOM.style.t`. Maybe it's my fault but I only managed to make them work using `Obj.magic` on a `ReactDOMStyle.make` function. 
https://github.com/cca-io/rescript-material-ui/blob/2d76be046a25060ee817f67bea54a9d2448276ed/public/rescript-material-ui/src/MaterialUi_ThemeOptions.res#L109-L111

Hope you will find the issue useful and excuse me if it has been just me not using them right.

**Comment by jsiebern** [comment]
Hi, even though I'm not the primary maintainer anymore I should be able to answer this for you. Your use of `Obj.magic` is the correct approach here. This is not ideal but the theme definitions of Mui are immenseley complex and the TS type system unfortunately has no option of comprehensively exposing a tree of types. So the generation of the theme bindings are and probably always will be a best effort approximation. Thank you for understanding.

**Comment by Deydim** [comment]
Glitches of this sort are totally OK and easy to slove. I just wanted to contribute with a bug report but now I see it's a well known thing. Thanks for the explanation!
