### ISSUE TITLE
Namespace: MaterialUi -> Mui

### ISSUE THREAD

**Issue by cknitt** [cca-io/rescript-material-ui#174]
IMHO we should change the namespace from `MaterialUi` to `Mui` in 3.0.0 for the following reasons:

1. Nice and short 🙂
2. Material-UI [rebranded to MUI](https://mui.com/blog/material-ui-is-now-mui/)
3. Now that we are using the `namespace` feature in bsconfig.json, it is not possible anymore for the user to "alias" the `MaterialUi` module to `Mui` himself using `include MaterialUi`.
4. 3.0.0 already has other breaking changes anyway.

**Comment by fhammerschmidt** [comment]
Done, but leaving it open so that we do not forget to mention it in the docs.

**Comment by fhammerschmidt** [comment]
Closing this, I put it already into the Draft PR (#177).
